spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nanoledger}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

server:
  port: ${PORT:8080}
